- hosts: localhost
  tasks:
    - name: Install Timetracker (Watson)
      become: yes
      package:
        name: Watson
        state: present
    - name: Install zsh
      become: yes
      package:
        name: zsh
        state: present
    - name: Install zsh-syntax-highlighting
      become: yes
      package:
        name: zsh-syntax-highlighting
        state: present
    - name: Install noto-fonts-emoji
      become: yes
      package:
        name: noto-fonts-emoji
        state: present
      ansible.builtin.shell: |
        mkdir ~/.config/fontconfig/fonts
        touch ~/.config/fontconfig/fonts.conf
        echo "<<-EOF
        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
        <fontconfig>
        <alias>
          <family>sans-serif</family>
          <prefer>
            <family>Noto Sans</family>
            <family>Noto Color Emoji</family>
            <family>Noto Emoji</family>
            <family>DejaVu Sans</family>
          </prefer>
        </alias>

        <alias>
          <family>serif</family>
          <prefer>
            <family>Noto Serif</family>
            <family>Noto Color Emoji</family>
            <family>Noto Emoji</family>
            <family>DejaVu Serif</family>
          </prefer>
        </alias>

        <alias>
          <family>monospace</family>
          <prefer>
            <family>Noto Mono</family>
            <family>Noto Color Emoji</family>
            <family>Noto Emoji</family>
          </prefer>
        </alias>
        </fontconfig>
        EOF" | ~/.config/fontconfig/fonts.conf
